// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if environment variables are set
const hasValidCredentials = 
  SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL !== 'your-project-url-here' &&
  SUPABASE_PUBLISHABLE_KEY !== 'your-anon-key-here' &&
  (SUPABASE_URL.startsWith('https://') || SUPABASE_URL.startsWith('http://')) &&
  SUPABASE_URL.includes('supabase.co');

if (!hasValidCredentials) {
  console.warn('⚠️ Supabase not configured. Please set up your .env file with valid credentials.');
  console.warn('Get your credentials from: https://supabase.com/dashboard/project/_/settings/api');
}

export const supabase = hasValidCredentials 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null as any; // Mock client for development without Supabase